Repository hollar/ex_ach, pull requests merged in 2018-03, with the labels that each got.

#8 Setup a new mix project
  README.md
  mix.exs
  mix.lock
Labels: chore, in-codereview

#3 Generate a batch header record
  .circleci/config.yml
  dialyzer.ignore-warnings
  lib/ex_ach.ex
  lib/ex_ach/ach.ex
  lib/ex_ach/batch.ex
  lib/ex_ach/batch_header.ex
  lib/ex_ach/batch_header_params.ex
  lib/ex_ach/field.ex
  lib/ex_ach/file_header.ex
  lib/ex_ach/file_header_params.ex
  mix.exs
  mix.lock
  test/ex_ach/batch_header_params_test.exs
  test/ex_ach/batch_test.exs
  test/ex_ach_test.exs
  test/support/test_case.ex
Labels: feature, in-progress

#4 Generate batch entry details records
  README.md
  lib/ex_ach/batch.ex
  lib/ex_ach/batch/entry/entry.ex
  lib/ex_ach/batch/entry/fields/addenda_record_indicator.ex
  lib/ex_ach/batch/entry/fields/amount.ex
  lib/ex_ach/batch/entry/fields/check_digit.ex
  lib/ex_ach/batch/entry/fields/dfi_account_number.ex
  lib/ex_ach/batch/entry/fields/discretionary_data.ex
  lib/ex_ach/batch/entry/fields/identification_number.ex
  lib/ex_ach/batch/entry/fields/receiving_company_name.ex
  lib/ex_ach/batch/entry/fields/receiving_dfi_identification.ex
  lib/ex_ach/batch/entry/fields/record_type.ex
  lib/ex_ach/batch/entry/fields/trace_number.ex
  lib/ex_ach/batch/entry/fields/transaction_code.ex
  test/ex_ach/batch/entry_test.exs
  test/ex_ach/file_test.exs
Labels: feature, in-codereview

#5 Generate a batch control record
  lib/ex_ach.ex
  lib/ex_ach/batch.ex
  lib/ex_ach/batch/control.ex
  lib/ex_ach/batch/control/fields/batch_number.ex
  lib/ex_ach/batch/control/fields/company_identification.ex
  lib/ex_ach/batch/control/fields/entry_addenda_count.ex
  lib/ex_ach/batch/control/fields/entry_hash.ex
  lib/ex_ach/batch/control/fields/message_authentication_code.ex
  lib/ex_ach/batch/control/fields/originating_dfi_identification.ex
  lib/ex_ach/batch/control/fields/record_type_code.ex
  lib/ex_ach/batch/control/fields/service_class_code.ex
  lib/ex_ach/batch/control/fields/total_credit_entry_dollar_amount.ex
  lib/ex_ach/batch/control/fields/total_debit_entry_dollar_amount.ex
  lib/ex_ach/batch/entry.ex
  lib/ex_ach/batch/entry/fields/dfi_account_number.ex
  lib/ex_ach/batch/entry/fields/discretionary_data.ex
  lib/ex_ach/batch/entry/fields/identification_number.ex
  lib/ex_ach/batch/entry/fields/receiving_company_name.ex
  lib/ex_ach/batch/entry/fields/receiving_dfi_identification.ex
  lib/ex_ach/batch/entry/fields/transaction_code.ex
  lib/ex_ach/batch/header.ex
  lib/ex_ach/batch/header/fields/company_discretionary_data.ex
  lib/ex_ach/batch/header/fields/company_entry_description.ex
  lib/ex_ach/batch/header/fields/company_name.ex
  lib/ex_ach/batch/header/fields/originating_dfi_identification.ex
  lib/ex_ach/field.ex
  lib/ex_ach/field_validator.ex
  lib/ex_ach/file/header/fields/immediate_destination.ex
  lib/ex_ach/file/header/fields/immediate_destination_name.ex
  lib/ex_ach/file/header/fields/immediate_origin.ex
  lib/ex_ach/file/header/fields/immediate_origin_name.ex
  lib/ex_ach/file/header/fields/reference_code.ex
  test/ex_ach/batch/control/fields/entry_addenda_count_test.exs
  test/ex_ach/batch/control/fields/entry_hash_test.exs
  test/ex_ach/batch/control/fields/total_credit_entry_dollar_amount_test.exs
  test/ex_ach/batch/control/fields/total_debit_entry_dollar_amount_test.exs
  test/ex_ach/batch/control_test.exs
  test/ex_ach/batch/entry_test.exs
  test/ex_ach/batch/header_test.exs
  test/ex_ach/batch_test.exs
  test/ex_ach/field_validator_test.exs
  test/ex_ach/file/header_test.exs
  test/ex_ach/file_test.exs
Labels: feature, in-progress

#16 Add ability to provide a date and time when creating a File
  lib/ex_ach.ex
  lib/ex_ach/file.ex
  lib/ex_ach/file/header.ex
  test/ex_ach/file/header_test.exs
Labels: feature, in-progress
